### PR TITLE
fix bug

### PR DESCRIPTION
**Pull request by dzy321**
`
function replacePlaceholdersRecursivelyIn (string) {
          if(typeof string !== 'string'){
            return string;
          }
          return string.replace(self.regex, function (match, index, gt) {
            // Check whether promise result must be escaped
            var resolvedValue = promiseResults[index]
            var result = gt === '>' ? resolvedValue : self.engine.escapeExpression(resolvedValue)
            return replacePlaceholdersRecursivelyIn(result)
          })
        }
`
when string is safestring ,throw error

### CODE REVIEW

**Comment by jskrzypek** [comment]
Hi, thanks for the PR. I think I might understand the problem your having, but I'm not sure.

Can you write please write up the issue you're having a bit more clearly or at least a short code sample of what you're doing that causes the error can be sufficient.

Cheers,
Josh

**Comment by dzy321** [comment]
hello,when helper return SafeString. function `replacePlaceholdersRecursivelyIn` will throw error.
for example:
`
handlebars.registerHelper('save', async function (args) {
        return new handlebars.SafeString('.....);
 }
`

**Comment by nknapp** [comment]
It would be most helpful if you could create a PR with a (failing) test [here](https://github.com/nknapp/promised-handlebars/blob/master/test/default-suite.js). That way we can see what the problem is and how to solve it. 

Make sure to use the [StandardJS](http://standardjs.com/index.html) code-style. Otherwise Travis won't even get to the tests. (I should change this some time, but at the moment, the code-style is checked before the tests are run).

**Comment by dzy321** [comment]
I add error test [here](https://github.com/dzy321/promised-handlebars/blob/master/test/default-suite.js)

**Comment by nknapp** [comment]
The test is good. However, I don't get an error when running the tests.
The template seems to return the an object instead of a string. I also could not reproduce that your original change fixes the problem. The test case returns the same result.

When you run `standard --fix` and check-in the result (see [this Travis build](https://travis-ci.org/nknapp/promised-handlebars/jobs/153156469#L217)), this should also be seen in Travis. Could you do that, just to be sure?

I'll open an issue for handling "Safestring"-objects correctly.

**Comment by nknapp** [comment]
The test succeeds (even without your fix) if the helper is not used as a block helper (`{{test}}`) but it fails for block-helper use (`{{#test}}{{/test}}`).

**Comment by nknapp** [comment]
The reference from commit 1b487e4 about the failing test is wrong. It should be #26

**Comment by nknapp** [comment]
I'm closing this PR becaus the issue is addressed in #25 and #27. 
The fix is a bit more complicated than proposed here. I have (roughly) taken the test from this PR and integrated it into the test-suite (renamed the helper and the test itself to something more meaningful).

@dzy321 Thank you for providing the test.Once #27 is merged and published, your problem should be resolved. I would like to give the other collaborators time for a review though.

**Pull request closed without merging**
